---
http_client_port: 2052
public_http_port: 2052
http_client_listen:
- 0.0.0.0
http_server_port: 2082
udp_server_port: 2700
database: jdbc:postgresql://db:5432/node1db?user=node1user&password=uniPass
node_number: 1
public_host: 127.0.0.1
node_name: node-1-local
ip:
- 127.0.0.1
ipv6:
- fdf0:e132:efcf:2fae::11
