---
http_client_port: 2052
http_client_listen:
- 0.0.0.0
http_server_port: 2082
udp_server_port: 2700
node_number: 3
public_host: node-3-local.universa.io
node_name: node-3-local.universa.io
ip:
- 10.6.0.13